In [17]:
import math

In [2]:
math.sqrt(25)

5.0

In [18]:
import numpy

In [6]:
 from scipy import stats

In [7]:
from numpy import random

In [19]:
import numpy as np

In [9]:
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)

In [10]:
print(dataOne)

[[0.24127693 0.89195873 0.69257731 0.05552311 0.7739907 ]
 [0.33012612 0.91107214 0.78143104 0.60982876 0.95124168]
 [0.35206357 0.90685661 0.80121149 0.50731761 0.18013347]
 [0.49763896 0.03349315 0.92866375 0.85579322 0.32160476]
 [0.97793656 0.87511721 0.62356394 0.12544383 0.13399913]]


In [11]:
np.mean(dataOne)

0.5743945512008211

In [12]:
np.std(dataOne)

0.31518960912623273

In [13]:
np.min(dataOne)

0.03349314758099775

In [14]:
np.max(dataOne)

0.9779365638778609

In [15]:
np.median(dataOne)

0.6235639413973418

In [16]:
np.summary(dataOne)

AttributeError: module 'numpy' has no attribute 'summary'

#  I could not use Numpy to get statistical summary for the whole array.

In [19]:
stats.describe(dataOne)

DescribeResult(nobs=5, minmax=(array([0.24127693, 0.03349315, 0.62356394, 0.05552311, 0.13399913]), array([0.97793656, 0.91107214, 0.92866375, 0.85579322, 0.95124168])), mean=array([0.47980843, 0.72369957, 0.76548951, 0.43078131, 0.47219395]), variance=array([0.0860176 , 0.14906958, 0.01340377, 0.11315015, 0.13573004]), skewness=array([ 1.15886608, -1.49501334,  0.20675304,  0.01211725,  0.3935884 ]), kurtosis=array([-0.23042176,  0.24327274, -1.00905514, -1.4814787 , -1.61189865]))

In [21]:
print(stats.describe(dataOne))

DescribeResult(nobs=5, minmax=(array([0.24127693, 0.03349315, 0.62356394, 0.05552311, 0.13399913]), array([0.97793656, 0.91107214, 0.92866375, 0.85579322, 0.95124168])), mean=array([0.47980843, 0.72369957, 0.76548951, 0.43078131, 0.47219395]), variance=array([0.0860176 , 0.14906958, 0.01340377, 0.11315015, 0.13573004]), skewness=array([ 1.15886608, -1.49501334,  0.20675304,  0.01211725,  0.3935884 ]), kurtosis=array([-0.23042176,  0.24327274, -1.00905514, -1.4814787 , -1.61189865]))


In [22]:
print('I love Date Science')

I love Date Science


In [23]:
variablename1 = 'I Love Data Science'

In [24]:
print (variablename1)

I Love Data Science


In [25]:
variableName=25

In [26]:
print (variableName)

25


In [27]:
type(variableName)

int

In [4]:
varOne=25

In [3]:
varTwo=25.0

In [30]:
varThree=varOne+varTwo

In [31]:
print(varThree)

50.0


In [5]:
varTwo='Hello'

In [8]:
varThree=str(varOne)+varTwo
varThree

'25Hello'

In [34]:
print(varTwo)

Hello


In [43]:
varThree = 'varOne'+varTwo

In [44]:
print (varThree)

varOneHello


In [46]:
str(varOne)

'25'

In [48]:
type(varOne)

int

In [50]:
varOne=str(varOne)

In [51]:
varThree=varOne+varTwo

In [52]:
print(varThree)

25Hello


In [53]:
listone=[1,2,3,4]

In [54]:
print(listone)

[1, 2, 3, 4]


In [55]:
print(listone[1:3])

[2, 3]


In [16]:
tel = {'jack': 4098, 'sape': 4139}

In [57]:
tel['jack']

4098

In [9]:
price={'p1':2,'p2':3,'p3':5,'p4':6,'p5':8,'p6':9}

In [11]:
price['p1']

2

In [13]:
highprice = price['p1']+1
highprice

3

In [34]:
pricevalue = price.values()
pricevalue

dict_values([2, 3, 5, 6, 8, 9])

In [36]:
pricevalue

dict_values([2, 3, 5, 6, 8, 9])

In [18]:
sum_dict = tel['jack']+tel['sape']
sum_dict

8237

In [27]:
price5 = price.values()
price5

dict_values([2, 3, 5, 6, 8, 9])

In [25]:
print(price2)

[ 3  4  6  7  9 10]


In [64]:
price2=price[0:3]+1

In [65]:
print(price2)

[3 4 6]


In [66]:
price3=price[0:3]/2

In [67]:
print(price3)

[1.  1.5 2.5]


In [68]:
price4=price[0:3]%3

In [69]:
print(price4)

[2 0 2]


In [3]:
import pandas as pd

In [13]:
sales = pd.read_csv(r'C:\Users\kylie\Documents\UT Data Analysis Course\Course Two\Task 2\CompleteResponses.csv')

In [14]:
sales.head()

salary  age  elevel  car  zipcode        credit  brand
0  119806.54480   45       0   14        4  442037.71130      0
1  106880.47840   63       1   11        6   45007.17883      1
2   78020.75094   23       0   15        2   48795.32279      0
3   63689.93635   51       3    6        5   40888.87736      1
4   50873.61880   20       3   14        4  352951.49770      0